use test
drop table if exists tmlz5d_cd;
create table if not exists tmlz5d_cd(
id MEDIUMINT NOT NULL AUTO_INCREMENT,
title varchar(1000) NOT NULL,
artist varchar(1000) NOT NULL,
year varchar(4) NOT NULL,
PRIMARY KEY (id)
);
insert into tmlz5d_cd (title, artist, year) values ("CD Title"," Artist Name","Year Released");
insert into tmlz5d_cd (title, artist, year) values ("Koi No Yokan","Deftones","2012");
insert into tmlz5d_cd (title, artist, year) values ("21","Adele","2011");
insert into tmlz5d_cd (title, artist, year) values ("How to Save a Life","The Fray","2005");
insert into tmlz5d_cd (title, artist, year) values ("Spider-Man Soundtrack","Various Artists","2002");
insert into tmlz5d_cd (title, artist, year) values ("Atlas","Parkway Drive","2012");
insert into tmlz5d_cd (title, artist, year) values ("The Moment","Framing Hanley","2007");
insert into tmlz5d_cd (title, artist, year) values ("The Battle of Los Angeles","Rage Against the Machine","1999");
insert into tmlz5d_cd (title, artist, year) values ("Something Like Human","Fuel","2000");
insert into tmlz5d_cd (title, artist, year) values ("Black Diamonds","Issues","2012");
insert into tmlz5d_cd (title, artist, year) values ("Outcasts","Palisades","2013");
insert into tmlz5d_cd (title, artist, year) values ("Collapse","Dangerkids","2013");
insert into tmlz5d_cd (title, artist, year) values ("Chapter V","Trey Songz","2012");
insert into tmlz5d_cd (title, artist, year) values ("Violence","Tear Out the Heart","2013");
insert into tmlz5d_cd (title, artist, year) values ("Know Hope","The Color Morale","2013");
insert into tmlz5d_cd (title, artist, year) values ("Rise Records-200","Various Artists","2013");
insert into tmlz5d_cd (title, artist, year) values ("Tony Hawk's American Wasteland Soundtrack","Various Artists","2005");
insert into tmlz5d_cd (title, artist, year) values ("Watching Judas","Watching Judas","2007");
insert into tmlz5d_cd (title, artist, year) values ("Saints","Destroy the Runner","2006");
insert into tmlz5d_cd (title, artist, year) values ("Evanescence (S/T)","Evanescence","2011");
insert into tmlz5d_cd (title, artist, year) values ("In Fear and Faith (S/T)","In Fear and Faith","2012");
insert into tmlz5d_cd (title, artist, year) values ("Minus the Machine","10 Years","2012");
insert into tmlz5d_cd (title, artist, year) values ("The Sufferer and The Witness","Rise Against","2006");
insert into tmlz5d_cd (title, artist, year) values ("Fallen Empires","Snow Patrol","2011");
insert into tmlz5d_cd (title, artist, year) values ("Fragile Figures","Secrets","2013");
insert into tmlz5d_cd (title, artist, year) values ("Periphery II - This Time It's Personal","Periphery","2012");
insert into tmlz5d_cd (title, artist, year) values ("Periphery I (S/T)","Periphery","2010");
insert into tmlz5d_cd (title, artist, year) values ("A War You Cannot Win","All That Remains","2012");
insert into tmlz5d_cd (title, artist, year) values ("Love Album Parts One and Two (Dual Disc)","Angels and Airwaves","2011");
insert into tmlz5d_cd (title, artist, year) values ("Punk Goes Pop Volume 5","Various Artists","2012");
insert into tmlz5d_cd (title, artist, year) values ("Punk Goes Pop Volume 4","Various Artists","2011");
insert into tmlz5d_cd (title, artist, year) values ("End of Silence","Red","2006");
insert into tmlz5d_cd (title, artist, year) values ("Release the Panic","Red","2013");
insert into tmlz5d_cd (title, artist, year) values ("Riot!","Paramore","2007");
insert into tmlz5d_cd (title, artist, year) values ("Paramore (S/T)","Paramore","2013");
insert into tmlz5d_cd (title, artist, year) values ("The Hollow","Memphis May Fire","2011");
insert into tmlz5d_cd (title, artist, year) values ("Challenger","Memphis May Fire","2012");
insert into tmlz5d_cd (title, artist, year) values ("Scary Monsters and Nice Sprites","Skrillex","2010");
insert into tmlz5d_cd (title, artist, year) values ("Bangarang","Skrillex","2012");
insert into tmlz5d_cd (title, artist, year) values ("Wonder What's Next","Chevelle","2002");
insert into tmlz5d_cd (title, artist, year) values ("Hats Off To The Bull","Chevelle","2011");
insert into tmlz5d_cd (title, artist, year) values ("Point #1","Chevelle","1999");
insert into tmlz5d_cd (title, artist, year) values ("Endless Winter","Steryle","2012");
insert into tmlz5d_cd (title, artist, year) values ("Severance","Steryle","2007");
insert into tmlz5d_cd (title, artist, year) values ("Foreshadowing Yesterday","Steryle","2009");
insert into tmlz5d_cd (title, artist, year) values ("Foreshadowing Yesterday","Steryle","2009");
insert into tmlz5d_cd (title, artist, year) values ("Attack Attack! (Self-Titled) Deluxe Reissue","Attack Attack!","2011");
insert into tmlz5d_cd (title, artist, year) values ("Attack Attack! (S/T)","Attack Attack!","2010");
insert into tmlz5d_cd (title, artist, year) values ("Someday Came Suddenly","Attack Attack!","2008");
insert into tmlz5d_cd (title, artist, year) values ("The Fake Sound of Progress","Lostprophets","2001");
insert into tmlz5d_cd (title, artist, year) values ("Start Something","Lostprophets","2003");
insert into tmlz5d_cd (title, artist, year) values ("Random Access Memories","Daft Punk","2013");
insert into tmlz5d_cd (title, artist, year) values ("Tron Legacy Soundtrack","Daft Punk","2010");
insert into tmlz5d_cd (title, artist, year) values ("Tron Legacy Reconfigured","Daft Punk/Various Artists","2011");
insert into tmlz5d_cd (title, artist, year) values ("Understanding What We've Grown to Be","We Came as Romans","2011");
insert into tmlz5d_cd (title, artist, year) values ("Tracing Back Roots","We Came as Romans","2013");
insert into tmlz5d_cd (title, artist, year) values ("Understanding What We've Grown to Be- Deluxe Reissue","We Came as Romans","2013");
insert into tmlz5d_cd (title, artist, year) values ("No Apologies","Trapt","2010");
insert into tmlz5d_cd (title, artist, year) values ("Only Through the Pain…","Trapt","2008");
insert into tmlz5d_cd (title, artist, year) values ("Trapt (S/T)","Trapt","2002");
insert into tmlz5d_cd (title, artist, year) values ("Someone in Control","Trapt","2005");
insert into tmlz5d_cd (title, artist, year) values ("Hello Nasty","Beastie Boys","1998");
insert into tmlz5d_cd (title, artist, year) values ("Licensed to Ill","Beastie Boys","1986");
insert into tmlz5d_cd (title, artist, year) values ("HotSauceCommitteePartTwo","Beastie Boys","2011");
insert into tmlz5d_cd (title, artist, year) values ("Sempiternal","Bring Me The Horizon","2013");
insert into tmlz5d_cd (title, artist, year) values ("Count Your Blessings (1 of 2-disc set)","Bring Me The Horizon","2006");
insert into tmlz5d_cd (title, artist, year) values ("This Is What The Edge of Your Seat Was Made For(2 of 2)","Bring Me The Horizon","2004");
insert into tmlz5d_cd (title, artist, year) values ("There Is A Hell Believe Me I've Seen It. There Is A Heaven Lets Keep It A Secret","Bring Me The Horizon","2010");
insert into tmlz5d_cd (title, artist, year) values ("Suicide Season (Japan Import)","Bring Me The Horizon","2010");
insert into tmlz5d_cd (title, artist, year) values ("To Plant A Seed","We Came As Romans","2009");
insert into tmlz5d_cd (title, artist, year) values ("When We Don't Exist","Like Moths to Flames","2011");
insert into tmlz5d_cd (title, artist, year) values ("An Eye For An Eye","Like Moths to Flames","2013");
insert into tmlz5d_cd (title, artist, year) values ("Dead Throne","The Devil Wears Prada","2011");
insert into tmlz5d_cd (title, artist, year) values ("Zombie EP","The Devil Wears Prada","2010");
insert into tmlz5d_cd (title, artist, year) values ("Life Cycles","The Word Alive","2012");
insert into tmlz5d_cd (title, artist, year) values ("Deceiver","The Word Alive","2010");
insert into tmlz5d_cd (title, artist, year) values ("Truth and Purpose","I The Breather","2012");
insert into tmlz5d_cd (title, artist, year) values ("These Are My Sins","I The Breather","2010");
insert into tmlz5d_cd (title, artist, year) values ("We Come In Numbers EP","It Lives, It Breathes","2013");
insert into tmlz5d_cd (title, artist, year) values ("Sojourner","Forevermore","2012");
insert into tmlz5d_cd (title, artist, year) values ("Moths and Rust","Forevermore","2010");
insert into tmlz5d_cd (title, artist, year) values ("The Crux","Hurt","2010");
insert into tmlz5d_cd (title, artist, year) values ("Emarosa (S/T)","Emarosa","2010");
insert into tmlz5d_cd (title, artist, year) values ("Find What You Love and Let It Kill You EP","Jonny Craig","2013");
insert into tmlz5d_cd (title, artist, year) values ("Soundtrack to Your Escape","In Flames","2004");
insert into tmlz5d_cd (title, artist, year) values ("Sounds of a Playground Fading","In Flames","2011");
insert into tmlz5d_cd (title, artist, year) values ("Ground Dweller","Hands Like Houses","2012");
insert into tmlz5d_cd (title, artist, year) values ("Take This To Your Grave","Fall Out Boy","2003");
insert into tmlz5d_cd (title, artist, year) values ("Stadium Arcadium","Red Hot Chili Peppers","2006");
insert into tmlz5d_cd (title, artist, year) values ("Let The Future Tell The Truth","I Am Abomination","2013");
insert into tmlz5d_cd (title, artist, year) values ("Staind (S/T)","Staind","2011");
insert into tmlz5d_cd (title, artist, year) values ("Chapter V","Staind","2005");
insert into tmlz5d_cd (title, artist, year) values ("14 Shades of Grey","Staind","2003");
insert into tmlz5d_cd (title, artist, year) values ("Break the Cycle","Staind","2001");
insert into tmlz5d_cd (title, artist, year) values ("Dysfunction","Staind","1999");
insert into tmlz5d_cd (title, artist, year) values ("In The Wake of Determination","Story of the Year","2005");
insert into tmlz5d_cd (title, artist, year) values ("The Black Swan","Story of the Year","2008");
insert into tmlz5d_cd (title, artist, year) values ("Children of Fire","Oh, Sleeper","2011");
insert into tmlz5d_cd (title, artist, year) values ("Son of the Morning","Oh, Sleeper","2009");
insert into tmlz5d_cd (title, artist, year) values ("The Titan EP","Oh, Sleeper","2013");
insert into tmlz5d_cd (title, artist, year) values ("At Heart","Miss May I","2012");
insert into tmlz5d_cd (title, artist, year) values ("Monument","Miss May I","2010");
insert into tmlz5d_cd (title, artist, year) values ("Hell Is What You Make It","Breathe Carolina","2011");
insert into tmlz5d_cd (title, artist, year) values ("It's Classy Not Classic","Breathe Carolina","2008");
insert into tmlz5d_cd (title, artist, year) values ("Hello Fascination","Breathe Carolina","2009");
insert into tmlz5d_cd (title, artist, year) values ("Storm the Gates of Hell","Demon Hunter","2007");
insert into tmlz5d_cd (title, artist, year) values ("Demon Hunter (S/T)","Demon Hunter","2002");
insert into tmlz5d_cd (title, artist, year) values ("True Defiance","Demon Hunter","2012");
insert into tmlz5d_cd (title, artist, year) values ("Neck of the Woods","Silversun Pickups","2012");
insert into tmlz5d_cd (title, artist, year) values ("Warped Tour Compilation 2011","Various Artists","2011");
insert into tmlz5d_cd (title, artist, year) values ("Warped Tour Compilation 2013","Various Artists","2013");
insert into tmlz5d_cd (title, artist, year) values ("Warped Tour Compilation 2012","Various Artists","2012");
insert into tmlz5d_cd (title, artist, year) values ("Could You Watch Your Children Burn","The Plot In You","2013");
insert into tmlz5d_cd (title, artist, year) values ("Nightlife","Skip The Foreplay","2012");
insert into tmlz5d_cd (title, artist, year) values ("The Very Best of Mudvayne","Mudvayne","2011");
insert into tmlz5d_cd (title, artist, year) values ("Blood","In This Moment","2012");
insert into tmlz5d_cd (title, artist, year) values ("Frequencies","Eyes Like Diamonds","2011");
insert into tmlz5d_cd (title, artist, year) values ("Siberia","Lights","2011");
insert into tmlz5d_cd (title, artist, year) values ("7th Symphony","Apocalyptica","2010");
insert into tmlz5d_cd (title, artist, year) values ("(AE)nima","Tool","1996");
insert into tmlz5d_cd (title, artist, year) values ("Awakening","Blessthefall","2011");
insert into tmlz5d_cd (title, artist, year) values ("Limitless","Crown the Empire","2011");
insert into tmlz5d_cd (title, artist, year) values ("The Fallout","Crown the Empire","2012");
insert into tmlz5d_cd (title, artist, year) values ("Collide","Skillet","2004");
insert into tmlz5d_cd (title, artist, year) values ("The Flood","Of Mice & Men","2011");
insert into tmlz5d_cd (title, artist, year) values ("The Flood Deluxe Reissue","Of Mice & Men","2012");
insert into tmlz5d_cd (title, artist, year) values ("Halcyon","Ellie Goulding","2012");
insert into tmlz5d_cd (title, artist, year) values ("Bright Lights","Ellie Goulding","2010");
insert into tmlz5d_cd (title, artist, year) values ("Number[s] Deluxe Reissue","Woe, Is Me","2012");
insert into tmlz5d_cd (title, artist, year) values ("American Dream","Woe, Is Me","2013");
insert into tmlz5d_cd (title, artist, year) values ("Genesi[s]","Woe, Is Me","2012");
insert into tmlz5d_cd (title, artist, year) values ("To Create A Cure","My Ticket Home","2012");
insert into tmlz5d_cd (title, artist, year) values ("Strangers Only","My Ticket Home","2013");
insert into tmlz5d_cd (title, artist, year) values ("Geeving","Abandon All Ships","2010");
insert into tmlz5d_cd (title, artist, year) values ("Infamous","Abandon All Ships","2012");
insert into tmlz5d_cd (title, artist, year) values ("Fire From the Tomb","War of Ages","2007");
insert into tmlz5d_cd (title, artist, year) values ("Pride of the Wicked","War of Ages","2006");
insert into tmlz5d_cd (title, artist, year) values ("Arise and Conquer","War of Ages","2008");
insert into tmlz5d_cd (title, artist, year) values ("Eternal","War of Ages","2010");
insert into tmlz5d_cd (title, artist, year) values ("Return to Life","War of Ages","2012");
insert into tmlz5d_cd (title, artist, year) values ("Disarm The Descent Special Edition","Killswitch Engage","2013");
insert into tmlz5d_cd (title, artist, year) values ("The Royal Thousand","Glass Cloud","2012");
insert into tmlz5d_cd (title, artist, year) values ("Perfect War Forever","Glass Cloud","2013");
insert into tmlz5d_cd (title, artist, year) values ("Meteora","Linkin Park","2003");
insert into tmlz5d_cd (title, artist, year) values ("Hybrid Theory","Linkin Park","2000");
insert into tmlz5d_cd (title, artist, year) values ("Reanimation","Linkin Park","2002");
insert into tmlz5d_cd (title, artist, year) values ("Hollow Bodies","Blessthefall","2013");
insert into tmlz5d_cd (title, artist, year) values ("8:18","The Devil Wears Prada","2013");
insert into tmlz5d_cd (title, artist, year) values ("The Fallout + Limitless Deluxe Reissue","Crown the Empire","2013");
insert into tmlz5d_cd (title, artist, year) values ("New Demons","I See Stars","2013");
insert into tmlz5d_cd (title, artist, year) values ("This Means War","Attack Attack!","2012");
insert into tmlz5d_cd (title, artist, year) values ("Sick [EP]","Beartooth","2013");
insert into tmlz5d_cd (title, artist, year) values ("Altered State","TesseracT","2013");
select * from tmlz5d_cd;

